"""
Planning & Supply Pydantic schemas.

Request/response models for API validation and serialization.
"""

import uuid
from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


# ============================================================================
# Forecast Schemas
# ============================================================================

class ForecastBase(BaseModel):
    """Base schema for Forecast."""

    name: str = Field(..., max_length=255, description="Forecast name")
    description: Optional[str] = Field(None, description="Forecast description")
    version: str = Field(..., max_length=50, description="Forecast version (e.g., 'v1.0', '2024-Q1')")
    product_id: Optional[uuid.UUID] = Field(None, description="Product ID (from Brand context)")
    sku_id: Optional[uuid.UUID] = Field(None, description="SKU ID (from Brand context)")
    start_date: datetime = Field(..., description="Forecast start date")
    end_date: datetime = Field(..., description="Forecast end date")
    method: str = Field(default="ai_ml", description="Forecast method")
    forecast_data: dict[str, Any] = Field(..., description="Forecast time series data (JSONB)")
    accuracy_metrics: Optional[dict[str, Any]] = Field(None, description="Accuracy metrics (if available)")
    generated_by_ai: bool = Field(default=False, description="Was this forecast generated by AI?")
    ai_model_version: Optional[str] = Field(None, description="AI model version")


class ForecastCreate(ForecastBase):
    """Schema for creating a forecast."""

    created_by: str = Field(..., max_length=255, description="User who created the forecast")
    parent_forecast_id: Optional[uuid.UUID] = Field(None, description="Parent forecast ID (for versioning)")


class ForecastUpdate(BaseModel):
    """Schema for updating a forecast."""

    name: Optional[str] = Field(None, max_length=255)
    description: Optional[str] = None
    forecast_data: Optional[dict[str, Any]] = None
    accuracy_metrics: Optional[dict[str, Any]] = None
    status: Optional[str] = None


class ForecastResponse(ForecastBase):
    """Schema for forecast response."""

    id: uuid.UUID
    tenant_id: uuid.UUID
    status: str
    created_by: str
    approved_by: Optional[str] = None
    approved_at: Optional[datetime] = None
    parent_forecast_id: Optional[uuid.UUID] = None
    ai_suggestion_id: Optional[uuid.UUID] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# ============================================================================
# Production Plan Schemas
# ============================================================================

class ProductionPlanBase(BaseModel):
    """Base schema for ProductionPlan."""

    plan_name: str = Field(..., max_length=255, description="Plan name")
    description: Optional[str] = Field(None, description="Plan description")
    start_date: datetime = Field(..., description="Planning period start")
    end_date: datetime = Field(..., description="Planning period end")
    forecast_id: Optional[uuid.UUID] = Field(None, description="Linked forecast ID")
    line_ids: Optional[list[str]] = Field(None, description="Production line IDs included in plan")
    plan_data: dict[str, Any] = Field(..., description="Production schedule data (JSONB)")
    capacity_analysis: Optional[dict[str, Any]] = Field(None, description="Capacity utilization analysis")
    constraints: Optional[dict[str, Any]] = Field(None, description="Constraints and conflicts")
    generated_by_ai: bool = Field(default=False, description="Was this plan generated by AI?")
    ai_optimizations: Optional[dict[str, Any]] = Field(None, description="AI optimization suggestions")


class ProductionPlanCreate(ProductionPlanBase):
    """Schema for creating a production plan."""

    created_by: str = Field(..., max_length=255, description="User who created the plan")


class ProductionPlanUpdate(BaseModel):
    """Schema for updating a production plan."""

    plan_name: Optional[str] = Field(None, max_length=255)
    description: Optional[str] = None
    plan_data: Optional[dict[str, Any]] = None
    capacity_analysis: Optional[dict[str, Any]] = None
    constraints: Optional[dict[str, Any]] = None
    status: Optional[str] = None
    completion_percentage: Optional[float] = Field(None, ge=0, le=100)


class ProductionPlanResponse(ProductionPlanBase):
    """Schema for production plan response."""

    id: uuid.UUID
    tenant_id: uuid.UUID
    status: str
    created_by: str
    approved_by: Optional[str] = None
    approved_at: Optional[datetime] = None
    execution_start: Optional[datetime] = None
    execution_end: Optional[datetime] = None
    completion_percentage: Optional[float] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# ============================================================================
# Safety Stock Schemas
# ============================================================================

class SafetyStockBase(BaseModel):
    """Base schema for SafetyStock."""

    product_id: Optional[uuid.UUID] = Field(None, description="Product ID")
    sku_id: Optional[uuid.UUID] = Field(None, description="SKU ID")
    ingredient_id: Optional[uuid.UUID] = Field(None, description="Ingredient ID (for raw materials)")
    plant_id: Optional[uuid.UUID] = Field(None, description="Plant ID")
    warehouse_location: Optional[str] = Field(None, max_length=255, description="Warehouse location")
    policy: str = Field(default="service_level", description="Safety stock calculation policy")
    safety_stock_quantity: float = Field(..., gt=0, description="Calculated safety stock quantity")
    unit: str = Field(default="units", max_length=50, description="Unit of measurement")
    target_service_level: Optional[float] = Field(None, ge=0, le=1, description="Target service level (0-1)")
    lead_time_days: Optional[float] = Field(None, gt=0, description="Lead time in days")
    demand_std_dev: Optional[float] = Field(None, ge=0, description="Demand standard deviation")
    demand_mean: Optional[float] = Field(None, ge=0, description="Mean demand")
    reorder_point: Optional[float] = Field(None, ge=0, description="Reorder point")
    calculation_details: Optional[dict[str, Any]] = Field(None, description="Calculation metadata")
    calculated_by_ai: bool = Field(default=False, description="Was this calculated by AI?")
    ai_confidence: Optional[float] = Field(None, ge=0, le=1, description="AI confidence score (0-1)")
    ai_reasoning: Optional[str] = Field(None, description="AI reasoning for recommendation")


class SafetyStockCreate(SafetyStockBase):
    """Schema for creating a safety stock recommendation."""

    pass


class SafetyStockUpdate(BaseModel):
    """Schema for updating a safety stock recommendation."""

    safety_stock_quantity: Optional[float] = Field(None, gt=0)
    unit: Optional[str] = Field(None, max_length=50)
    target_service_level: Optional[float] = Field(None, ge=0, le=1)
    lead_time_days: Optional[float] = Field(None, gt=0)
    reorder_point: Optional[float] = Field(None, ge=0)
    is_active: Optional[bool] = None
    last_reviewed: Optional[datetime] = None
    next_review_date: Optional[datetime] = None


class SafetyStockResponse(SafetyStockBase):
    """Schema for safety stock response."""

    id: uuid.UUID
    tenant_id: uuid.UUID
    is_active: bool
    last_reviewed: Optional[datetime] = None
    next_review_date: Optional[datetime] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# ============================================================================
# Inventory Level Schemas
# ============================================================================

class InventoryLevelBase(BaseModel):
    """Base schema for InventoryLevel."""

    product_id: Optional[uuid.UUID] = Field(None, description="Product ID")
    sku_id: Optional[uuid.UUID] = Field(None, description="SKU ID")
    ingredient_id: Optional[uuid.UUID] = Field(None, description="Ingredient ID")
    plant_id: Optional[uuid.UUID] = Field(None, description="Plant ID")
    warehouse_location: Optional[str] = Field(None, max_length=255, description="Warehouse location")
    on_hand_quantity: float = Field(default=0.0, ge=0, description="On-hand inventory quantity")
    available_quantity: float = Field(default=0.0, ge=0, description="Available (unallocated) quantity")
    allocated_quantity: float = Field(default=0.0, ge=0, description="Allocated quantity")
    in_transit_quantity: float = Field(default=0.0, ge=0, description="In-transit quantity")
    unit: str = Field(default="units", max_length=50, description="Unit of measurement")
    is_below_safety_stock: bool = Field(default=False, description="Is below safety stock level?")
    is_stockout: bool = Field(default=False, description="Is stock out?")
    days_of_supply: Optional[float] = Field(None, ge=0, description="Days of supply remaining")
    last_movement_type: Optional[str] = Field(None, max_length=50, description="Last movement type")
    last_movement_date: Optional[datetime] = Field(None, description="Last movement date")
    last_movement_quantity: Optional[float] = Field(None, description="Last movement quantity")
    as_of_date: datetime = Field(..., description="Snapshot date")


class InventoryLevelCreate(InventoryLevelBase):
    """Schema for creating an inventory level record."""

    pass


class InventoryLevelUpdate(BaseModel):
    """Schema for updating an inventory level record."""

    on_hand_quantity: Optional[float] = Field(None, ge=0)
    available_quantity: Optional[float] = Field(None, ge=0)
    allocated_quantity: Optional[float] = Field(None, ge=0)
    in_transit_quantity: Optional[float] = Field(None, ge=0)
    is_below_safety_stock: Optional[bool] = None
    is_stockout: Optional[bool] = None
    days_of_supply: Optional[float] = Field(None, ge=0)
    last_movement_type: Optional[str] = Field(None, max_length=50)
    last_movement_date: Optional[datetime] = None
    last_movement_quantity: Optional[float] = None


class InventoryLevelResponse(InventoryLevelBase):
    """Schema for inventory level response."""

    id: uuid.UUID
    tenant_id: uuid.UUID
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# ============================================================================
# Analytics Schemas
# ============================================================================

class ForecastAccuracyReport(BaseModel):
    """Forecast accuracy report schema."""

    forecast_id: uuid.UUID
    forecast_name: str
    forecast_version: str
    mape: Optional[float] = Field(None, description="Mean Absolute Percentage Error")
    mae: Optional[float] = Field(None, description="Mean Absolute Error")
    rmse: Optional[float] = Field(None, description="Root Mean Squared Error")
    bias: Optional[float] = Field(None, description="Forecast bias")
    periods_evaluated: int = Field(..., description="Number of periods evaluated")


class PlanningOverviewResponse(BaseModel):
    """Planning dashboard overview schema."""

    active_forecasts_count: int
    active_plans_count: int
    plans_pending_approval: int
    low_stock_items_count: int
    stockout_items_count: int
    avg_forecast_accuracy: Optional[float] = Field(None, description="Average MAPE across forecasts")
    total_inventory_value: Optional[float] = Field(None, description="Total inventory value (if available)")
    last_updated: datetime

